name: mine_lab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # localization (MUST be inside dependencies)
  flutter_localizations:
    sdk: flutter
  intl: any

  animated_bottom_navigation_bar: ^1.4.0
  awesome_dialog: ^3.3.0
  cached_network_image: 3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dotted_border: 2.1.0
  equatable: ^2.0.7
  file_picker: ^10.3.3
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^19.5.0
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.0
  flutter_widget_from_html: ^0.16.1
  get: ^4.7.2
  google_sign_in: ^7.1.1
  http: ^1.5.0
  rive_native: 0.0.17
  image_gallery_saver_plus: ^4.0.1
  lottie: 3.2.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  uuid: 4.5.1
  web: 1.1.1
  webview_flutter: 4.13.0
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    - assets/images/onboard/
    - assets/images/social/
    - assets/images/flags/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
